"""P4: apply a reviewer's corrections from TAMIL_REVIEW_PACK.xlsx back into ta.json.

Only rows with something in the Correction column are touched. Everything else is
left exactly as it is, so a partially reviewed pack is safe to apply.

Crop names live in the database, not the locale file: corrections on the
CROP NAMES sheet are reported and written to tamil_crop_corrections.sql for a
human to run, never applied automatically.

  python scripts/apply_tamil_corrections.py --pack TAMIL_REVIEW_PACK.xlsx --dry-run
  python scripts/apply_tamil_corrections.py --pack TAMIL_REVIEW_PACK.xlsx
"""
import argparse
import io
import json
import os
import re
import subprocess
import sys

from openpyxl import load_workbook

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MSG = os.path.join(ROOT, "govihub-web", "src", "messages")
SQL_OUT = os.path.join(ROOT, "tamil_crop_corrections.sql")

TOKEN = re.compile(r"\{([a-zA-Z0-9_]+)\}")
TAMIL = re.compile(r"[஀-௿]")


def flatten(obj, prefix=""):
    out = {}
    for k, v in obj.items():
        key = prefix + "." + k if prefix else k
        if isinstance(v, dict):
            out.update(flatten(v, key))
        else:
            out[key] = v
    return out


def unflatten(flat):
    root = {}
    for k, v in flat.items():
        parts = k.split(".")
        node = root
        for p in parts[:-1]:
            node = node.setdefault(p, {})
        node[parts[-1]] = v
    return root


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--pack", default=os.path.join(ROOT, "TAMIL_REVIEW_PACK.xlsx"))
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    if not os.path.exists(args.pack):
        print("pack not found: %s" % args.pack)
        return 1

    wb = load_workbook(args.pack, data_only=True)
    en = flatten(json.load(io.open(os.path.join(MSG, "en.json"), encoding="utf-8")))
    ta_nested = json.load(io.open(os.path.join(MSG, "ta.json"), encoding="utf-8"))
    ta = flatten(ta_nested)

    applied, skipped_same, rejected, crop_fixes, unknown = [], 0, [], [], []

    for name in wb.sheetnames:
        if name == "READ ME FIRST":
            continue
        ws = wb[name]
        header = [(c.value or "") for c in ws[1]]
        try:
            i_key = header.index("Key")
            i_corr = next(i for i, h in enumerate(header) if str(h).startswith("Correction"))
        except (ValueError, StopIteration):
            print("  skipping sheet %r - unexpected header" % name)
            continue

        for row in ws.iter_rows(min_row=2, values_only=True):
            if row is None or i_key >= len(row):
                continue
            key = row[i_key]
            corr = row[i_corr] if i_corr < len(row) else None
            if not key or corr is None or not str(corr).strip():
                continue
            corr = str(corr).strip()

            if name == "CROP NAMES":
                crop_fixes.append((str(key), corr))
                continue

            key = str(key).strip()
            if key not in en:
                unknown.append(key)
                continue
            if ta.get(key) == corr:
                skipped_same += 1
                continue
            # a correction must not break interpolation
            want = sorted(set(TOKEN.findall(en[key])))
            got = sorted(set(TOKEN.findall(corr)))
            if want != got:
                rejected.append((key, want, got))
                continue
            applied.append((key, ta.get(key, ""), corr))
            ta[key] = corr

    print("corrections found and applicable : %d" % len(applied))
    print("already matched current value    : %d" % skipped_same)
    print("rejected (placeholder mismatch)  : %d" % len(rejected))
    print("unknown keys (not in en.json)    : %d" % len(unknown))
    print("crop-name corrections (database) : %d" % len(crop_fixes))

    for k, want, got in rejected[:10]:
        print("   REJECT %s  needs %s, correction had %s" % (k, want, got))
    for k in unknown[:10]:
        print("   UNKNOWN %s" % k)

    if crop_fixes:
        with io.open(SQL_OUT, "w", encoding="utf-8") as f:
            f.write("-- Tamil crop-name corrections. Review, then run against govihub_spices.\n")
            f.write("-- Generated by scripts/apply_tamil_corrections.py\n")
            for key, corr in crop_fixes:
                code = key.split(".", 1)[1] if "." in key else key
                safe = corr.replace("'", "''")
                f.write("UPDATE crop_taxonomy SET name_ta = '%s' WHERE code = '%s';\n" % (safe, code))
        print("\ncrop-name SQL written (NOT executed): %s" % SQL_OUT)

    if args.dry_run:
        print("\nDRY RUN - ta.json not written")
        return 0

    if applied:
        merged = {k: ta[k] for k in en if k in ta}
        for k in ta:
            merged.setdefault(k, ta[k])
        with io.open(os.path.join(MSG, "ta.json"), "w", encoding="utf-8") as f:
            json.dump(unflatten(merged), f, ensure_ascii=False, indent=2)
            f.write("\n")
        print("\nta.json updated with %d corrections" % len(applied))
        for k, old, new in applied[:10]:
            print("   %s\n     was: %s\n     now: %s" % (k, old[:60], new[:60]))
    else:
        print("\nno applicable corrections - ta.json untouched")

    print("\n" + "=" * 52)
    print("re-running GT.1-GT.4")
    print("=" * 52)
    r = subprocess.run([sys.executable, os.path.join(ROOT, "scripts", "tamil_gates.py")],
                       env=dict(os.environ, PYTHONIOENCODING="utf-8", PYTHONUTF8="1"))
    return r.returncode


if __name__ == "__main__":
    sys.exit(main())
