#!/usr/bin/env bash
# =============================================================================
# GoviHub SSL Initialization
# Sets up Let's Encrypt SSL certificates via Certbot for all domains.
# Run once on initial server setup, then certificates auto-renew.
# =============================================================================

set -euo pipefail

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

PRIMARY_DOMAIN="${PRIMARY_DOMAIN:-govihublk.com}"
DOMAINS=(
  "govihublk.com"
  "www.govihublk.com"
  "govihub.lk"
  "www.govihub.lk"
)
ADMIN_EMAIL="${ADMIN_EMAIL:-admin@govihublk.com}"
STAGING="${STAGING:-false}"
CERTBOT_DATA_DIR="${CERTBOT_DATA_DIR:-/opt/govihub/certbot}"
NGINX_CONF_DIR="${NGINX_CONF_DIR:-/opt/govihub/nginx/conf.d}"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

log_info()    { echo -e "${BLUE}[INFO]${NC}  $*"; }
log_success() { echo -e "${GREEN}[OK]${NC}    $*"; }
log_warn()    { echo -e "${YELLOW}[WARN]${NC}  $*"; }
log_error()   { echo -e "${RED}[ERROR]${NC} $*" >&2; }

# ---------------------------------------------------------------------------
# Check prerequisites
# ---------------------------------------------------------------------------

log_info "=== Checking prerequisites ==="

if ! command -v docker &>/dev/null; then
  log_error "Docker is not installed"
  exit 1
fi

if ! command -v docker compose &>/dev/null; then
  log_error "Docker Compose is not installed"
  exit 1
fi

# Validate DNS resolution for all domains
log_info "Validating DNS for domains..."
DOMAIN_ARGS=""
for domain in "${DOMAINS[@]}"; do
  if ! host "$domain" &>/dev/null; then
    log_warn "DNS resolution failed for $domain — skipping"
    continue
  fi
  log_success "  $domain resolves correctly"
  DOMAIN_ARGS="$DOMAIN_ARGS -d $domain"
done

if [[ -z "$DOMAIN_ARGS" ]]; then
  log_error "No domains resolved — check DNS configuration"
  exit 1
fi

# ---------------------------------------------------------------------------
# Step 1: Create certbot directory structure
# ---------------------------------------------------------------------------

log_info "=== Step 1: Creating certbot directories ==="

mkdir -p "$CERTBOT_DATA_DIR/conf"
mkdir -p "$CERTBOT_DATA_DIR/www"
mkdir -p "$CERTBOT_DATA_DIR/log"

log_success "Certbot directories created"

# ---------------------------------------------------------------------------
# Step 2: Start Nginx with HTTP-only config (for ACME challenge)
# ---------------------------------------------------------------------------

log_info "=== Step 2: Starting Nginx for ACME challenge ==="

# Write temporary HTTP-only nginx config
cat > "$NGINX_CONF_DIR/govihub-acme.conf" << 'EOF'
server {
    listen 80;
    server_name _;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
        try_files $uri =404;
    }

    location / {
        return 200 'ACME challenge server';
        add_header Content-Type text/plain;
    }
}
EOF

# Start (or reload) nginx
docker compose up -d nginx 2>/dev/null || true
sleep 3

log_success "Nginx started for ACME challenge"

# ---------------------------------------------------------------------------
# Step 3: Run Certbot
# ---------------------------------------------------------------------------

log_info "=== Step 3: Obtaining SSL certificates ==="

CERTBOT_CMD="certbot certonly --webroot"
CERTBOT_CMD="$CERTBOT_CMD --webroot-path=/var/www/certbot"
CERTBOT_CMD="$CERTBOT_CMD --email $ADMIN_EMAIL"
CERTBOT_CMD="$CERTBOT_CMD --agree-tos"
CERTBOT_CMD="$CERTBOT_CMD --no-eff-email"
CERTBOT_CMD="$CERTBOT_CMD $DOMAIN_ARGS"

if [[ "$STAGING" == "true" ]]; then
  log_warn "Using Let's Encrypt staging environment (for testing)"
  CERTBOT_CMD="$CERTBOT_CMD --staging"
fi

docker run --rm \
  -v "$CERTBOT_DATA_DIR/conf:/etc/letsencrypt" \
  -v "$CERTBOT_DATA_DIR/www:/var/www/certbot" \
  -v "$CERTBOT_DATA_DIR/log:/var/log/letsencrypt" \
  certbot/certbot $CERTBOT_CMD

log_success "SSL certificates obtained for: ${DOMAINS[*]}"

# ---------------------------------------------------------------------------
# Step 4: Set up auto-renewal via cron
# ---------------------------------------------------------------------------

log_info "=== Step 4: Setting up certificate auto-renewal ==="

RENEWAL_SCRIPT="/opt/govihub/scripts/renew-ssl.sh"
cat > "$RENEWAL_SCRIPT" << 'RENEWAL_EOF'
#!/usr/bin/env bash
# Auto-generated by init-ssl.sh — do not edit
docker run --rm \
  -v /opt/govihub/certbot/conf:/etc/letsencrypt \
  -v /opt/govihub/certbot/www:/var/www/certbot \
  certbot/certbot renew --quiet --webroot \
  --webroot-path=/var/www/certbot \
  && docker compose -f /opt/govihub/docker-compose.yml exec nginx nginx -s reload
RENEWAL_EOF

chmod +x "$RENEWAL_SCRIPT"

# Add to root crontab (renew twice daily — Let's Encrypt recommendation)
CRON_ENTRY="0 3,15 * * * $RENEWAL_SCRIPT >> /var/log/govihub-ssl-renewal.log 2>&1"

if ! crontab -l 2>/dev/null | grep -qF "$RENEWAL_SCRIPT"; then
  (crontab -l 2>/dev/null; echo "$CRON_ENTRY") | crontab -
  log_success "Auto-renewal cron job added (runs at 03:00 and 15:00 daily)"
else
  log_warn "Auto-renewal cron job already exists"
fi

# ---------------------------------------------------------------------------
# Step 5: Clean up temp nginx config and reload with SSL
# ---------------------------------------------------------------------------

log_info "=== Step 5: Reloading Nginx with SSL configuration ==="

rm -f "$NGINX_CONF_DIR/govihub-acme.conf"
docker compose exec nginx nginx -s reload

log_success "Nginx reloaded with SSL"

# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------

echo ""
log_success "=== SSL INITIALIZATION COMPLETE ==="
log_info "Certificates: $CERTBOT_DATA_DIR/conf/live/$PRIMARY_DOMAIN/"
log_info "Auto-renewal: twice daily via cron"
log_info "Next step: verify HTTPS at https://$PRIMARY_DOMAIN"
